language: python

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

install:
  - python setup.py develop
  - pip install nose coverage coveralls

before_script:
  - cp test-settings.example.json test-settings.json

script:
  - nosetests --with-coverage --cover-package=netengine

after_success:
  coveralls
