language: python

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install qemu-system-arm curl

install:
  - python setup.py develop
  - pip install nose coverage coveralls

before_script:
  - cp test-settings.example.json test-settings.json
  - curl -LO http://downloads.openwrt.org/barrier_breaker/14.07/realview/generic/openwrt-realview-vmlinux-initramfs.elf
  - qemu-system-arm -M realview-eb-mpcore -kernel openwrt-realview-vmlinux-initramfs.elf -net nic -net user -nographic &
  - while sleep 1; do ping 10.0.2.15; 2>&1 && break; done


script:
  - nosetests --with-coverage --cover-package=netengine

after_success:
  coveralls
